name: Rust

on:
  workflow_call:
    # Can be called by other workflows to run the formatting and linting steps

permissions: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # Disable incremental compilation for faster from-scratch builds
  CARGO_PROFILE_TEST_DEBUG: 0 # Disable debug symbols for faster test builds

jobs:
  format-and-lint:
    name: Formatting & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          toolchain: stable

      - name: Build the project
        run: cargo build --locked --all-features --release

      - name: Run tests
        run: cargo test --locked --all-features --release